apiVersion: v2
name: kubecustos
description: A Helm chart for deploying the eBPF Runtime Security System.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami