# rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecustos-collector
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecustos-collector-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubecustos-collector-binding
subjects:
- kind: ServiceAccount
  name: kubecustos-collector
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubecustos-collector-role
  apiGroup: rbac.authorization.k8s.io