apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubecustos.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "kubecustos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics # Exposed port for Prometheus
  selector:
    app.kubernetes.io/name: {{ include "kubecustos.name" . }}
    app.kubernetes.io/component: backend