apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubecustos.fullname" . }}-collector-sa
  labels:
    {{- include "kubecustos.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubecustos.fullname" . }}-collector-cr
  labels:
    {{- include "kubecustos.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # Core API Group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubecustos.fullname" . }}-collector-crb
  labels:
    {{- include "kubecustos.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubecustos.fullname" . }}-collector-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubecustos.fullname" . }}-collector-cr
  apiGroup: rbac.authorization.k8s.io